name: "Aserto Build"
description: "Build policy bundle"
author: "Aserto.com"
branding:
  icon: box
  color: orange
inputs:
  source_path:
    description: "directory path to build input source"
    required: true
    default: src
  target_path:
    description: "directory path to build output directory"
    required: true
    default: build
  target_file:
    description: "build output filename"
    required: true
    default: bundle.tar.gz
  revision:
    description: "revision tag (GitHub SHA)"
    required: false
  build_options:
    description: "optional build options like --debug, --optimize, ..."
    required: false
  verbose:
    description: "verbose logging [ true | false ]"
    required: true
    default: "false"
runs:
  using: docker
  image: 'docker://ghcr.io/aserto-dev/aserto-one:action-v2'
  entrypoint: /app/build.sh
